# Generated by Django 3.2.3 on 2021-09-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ad_group_id', models.TextField()),
            ],
            options={
                'db_table': 'google_ad_groups',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key_word_id', models.TextField()),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.adgroups')),
            ],
            options={
                'db_table': 'google_key_words',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cost', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('cost_micros', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('search_rank_lost_impression_share', models.FloatField()),
                ('date', models.DateField()),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.keywords')),
            ],
            options={
                'db_table': 'google_metrics',
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_ads_token',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('google_id', models.CharField(max_length=250)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_clients',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('campaign_id', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.clients')),
            ],
            options={
                'db_table': 'google_campaigns',
            },
        ),
        migrations.AddField(
            model_name='adgroups',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.campaigns'),
        ),
    ]
