# Generated by Django 3.2.3 on 2021-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='google_id',
            field=models.CharField(default='0', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='campaigns',
            table='google_campaigns',
        ),
        migrations.AlterModelTable(
            name='clients',
            table='google_clients',
        ),
    ]
