# Generated by Django 3.2.3 on 2021-10-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0002_auto_20210916_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroups',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='metric',
        ),
    ]
