# Generated by Django 3.2.3 on 2021-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0002_auto_20210616_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='campaign_id',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
