# Generated by Django 3.2.3 on 2021-06-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0003_campaigns_campaign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ad_group_id', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.campaigns')),
            ],
            options={
                'db_table': 'google_ad_groups',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key_word_id', models.TextField()),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.adgroups')),
            ],
            options={
                'db_table': 'google_key_words',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cost', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('cost_micros', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('search_rank_lost_impression_share', models.FloatField()),
                ('date', models.DateField()),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.keywords')),
            ],
            options={
                'db_table': 'google_metrics',
            },
        ),
    ]
