# Generated by Django 3.2.3 on 2021-11-17 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_ads', '0003_auto_20211025_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googleadstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_token_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
