# Generated by Django 3.2.3 on 2021-11-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0004_auto_20211117_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='cost_micros',
            field=models.BigIntegerField(),
        ),
    ]
