# Generated by Django 3.2.3 on 2021-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0004_adgroups_keywords_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='impressions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
