# Generated by Django 3.2.3 on 2021-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0005_metrics_impressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
