# Generated by Django 3.2.3 on 2021-12-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0005_alter_metrics_cost_micros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['name']},
        ),
    ]
