# Generated by Django 3.2.3 on 2022-01-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0006_alter_clients_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='conversions',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='ctr',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='search_rank_lost_impression_share',
        ),
        migrations.AddField(
            model_name='metrics',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_ads.campaigns'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='key_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_ads.keywords'),
        ),
    ]
