# Generated by Django 3.2.3 on 2021-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0006_clients_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
