# Generated by Django 3.2.3 on 2022-04-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0007_auto_20220114_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='ad_group',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='key_word',
        ),
        migrations.DeleteModel(
            name='AdGroups',
        ),
        migrations.DeleteModel(
            name='KeyWords',
        ),
    ]
