version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8.17-alpine
    restart: always
    environment:
    ports:
      - 127.0.0.1:5672:5672
    env_file: ./ditexos/.env
  db:
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/databases:/var/lib/postgresql/data
    ports:
    - 127.0.0.1:5432:5432
  ditexos:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/home/www/
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
      - rabbitmq
    env_file: ./ditexos/.env
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ditexos
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ditexos/static/:/static
      - /etc/ssl/:/etc/ssl/
  celery_worker:
    restart: always
    build: ./docker/celery_worker
    command: celery -A ditexos worker --beat --scheduler ${DB_USER} --loglevel=info
    depends_on:
      - rabbitmq
      - db
      - ditexos
    volumes:
      - ./ditexos/.:/home/
    env_file: ./ditexos/.env