version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8.17-alpine
    restart: always
    environment:
      RABBITMQ_NODENAME: "django@localhost"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "django"
      RABBITMQ_DEFAULT_PASS: "12345"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5675:5672
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./docker/databases:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 5432:5432