# Generated by Django 3.2.3 on 2021-09-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_ads', '0002_auto_20210916_1554'),
        ('yandex_direct', '0001_initial'),
        ('calltouch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTouchReports',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calltouch.reports',),
        ),
        migrations.CreateModel(
            name='GoogleCampaigns',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('google_ads.campaigns',),
        ),
        migrations.CreateModel(
            name='GoogleClients',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('google_ads.clients',),
        ),
        migrations.CreateModel(
            name='GoogleKeyWords',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('google_ads.keywords',),
        ),
        migrations.CreateModel(
            name='YandexClients',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('yandex_direct.clients',),
        ),
    ]
