# Generated by Django 3.2.3 on 2022-03-02 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dashboard', '0001_initial'), ('dashboard', '0002_delete_googleclients'), ('dashboard', '0003_agencyclients'), ('dashboard', '0004_auto_20210917_1722'), ('dashboard', '0005_auto_20211014_0022'), ('dashboard', '0006_alter_agencyclients_call_tracker_type'), ('dashboard', '0007_auto_20211117_1301'), ('dashboard', '0008_alter_agencyclients_call_tracker_type'), ('dashboard', '0009_clientprojects'), ('dashboard', '0010_reporttypes'), ('dashboard', '0011_auto_20211230_1038'), ('dashboard', '0012_auto_20220121_1217'), ('dashboard', '0013_customizabledirection'), ('dashboard', '0014_alter_customizabledirection_direction'), ('dashboard', '0015_alter_customizabledirection_direction'), ('dashboard', '0016_auto_20220131_1819'), ('dashboard', '0017_auto_20220201_1605'), ('dashboard', '0018_agencyclients_my_target_client'), ('dashboard', '0019_alter_agencyclients_my_target_client'), ('dashboard', '0020_auto_20220221_2158'), ('dashboard', '0013_agencyclients_vk_client'), ('dashboard', '0014_alter_agencyclients_vk_client'), ('dashboard', '0021_merge_20220302_1614')]

    initial = True

    dependencies = [
        ('yandex_direct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_target', '0005_metrics_agency'),
        ('google_ads', '0002_auto_20210916_1554'),
        ('vk', '0004_auto_20220130_2046'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('vk', '0003_alter_metrics_spent'),
        ('calltouch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTouchReports',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('calltouch.reports',),
        ),
        migrations.CreateModel(
            name='GoogleCampaigns',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('google_ads.campaigns',),
        ),
        migrations.CreateModel(
            name='GoogleClients',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('google_ads.clients',),
        ),
        migrations.CreateModel(
            name='GoogleKeyWords',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('google_ads.keywords',),
        ),
        migrations.CreateModel(
            name='YandexClients',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('yandex_direct.clients',),
        ),
        migrations.DeleteModel(
            name='GoogleClients',
        ),
        migrations.CreateModel(
            name='AgencyClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_tracker_type', models.CharField(blank=True, choices=[('cl', 'CallTouch'), ('co_m', 'Comagic')], max_length=10, null=True, verbose_name='Тип коллтрекера')),
                ('crm_type', models.CharField(blank=True, choices=[('amo', 'AmoCrm'), ('exc', 'Excel')], max_length=10, null=True, verbose_name='Тип crm системы')),
                ('name', models.CharField(max_length=100, verbose_name='Название клиента')),
                ('google_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.clients', verbose_name='Логин клиента в google ads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_clients_user', to=settings.AUTH_USER_MODEL)),
                ('yandex_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.clients', verbose_name='Логин клиента в yandex direct')),
                ('my_target_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_target.clients', verbose_name='Логин клиента в my-target')),
                ('vk_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vk.clients', verbose_name='Логин клиента в vk ads')),
            ],
            options={
                'db_table': 'agency_clients',
            },
        ),
        migrations.DeleteModel(
            name='CallTouchReports',
        ),
        migrations.DeleteModel(
            name='GoogleCampaigns',
        ),
        migrations.DeleteModel(
            name='GoogleKeyWords',
        ),
        migrations.DeleteModel(
            name='YandexClients',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.agencyclients',),
        ),
        migrations.CreateModel(
            name='ClientProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('tag', models.CharField(max_length=256, verbose_name='Tag проекта в utm метке')),
                ('agency_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients')),
            ],
            options={
                'db_table': 'client_projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomizableDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, default='', max_length=256, verbose_name='Название кампании, по которому выделится направление')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование таблицы')),
                ('agency_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients')),
                ('is_main', models.BooleanField(default=False, verbose_name='Общее')),
            ],
            options={
                'db_table': 'customizable_direction',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ReportTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_common', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('is_channel', models.BooleanField(default=False, verbose_name='Статистика по каналам')),
                ('is_campaign', models.BooleanField(default=False, verbose_name='Статистика по кампаниям')),
                ('is_direction', models.BooleanField(default=False, verbose_name='Статистика по направлениям')),
                ('is_comagic_other', models.BooleanField(default=False, verbose_name='Статистика Comagic other')),
                ('is_period', models.BooleanField(default=False, verbose_name='Статистика по периодам')),
                ('is_project_channel', models.BooleanField(default=False, verbose_name='Статистика по каналам проекта')),
                ('is_project_by_day', models.BooleanField(default=False, verbose_name='Статистика по дням проекта')),
                ('agency_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients')),
                ('is_brand_nvm', models.BooleanField(default=False, verbose_name='Статистика за месяц для NVM')),
                ('is_month_nvm', models.BooleanField(default=False, verbose_name='Статистика по месяцам для NVM')),
                ('is_week_nvm', models.BooleanField(default=False, verbose_name='Статистика по неделям для NVM')),
                ('is_campaign_nvm', models.BooleanField(default=False, verbose_name='Статистика по кампаниям для NVM')),
                ('is_smm_nvm', models.BooleanField(default=False, verbose_name='Статистика по смм для NVM')),
                ('is_target_nvm', models.BooleanField(default=False, verbose_name='Статистика по таргетированной рекламе для NVM')),
            ],
            options={
                'db_table': 'report_types',
            },
        ),
    ]
