# Generated by Django 3.2.3 on 2022-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_squashed_0021_merge_20220302_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizabledirection',
            name='only_one_type',
            field=models.CharField(choices=[('br', 'Brand'), ('nb', 'No Brand'), ('all', 'All')], default='all', max_length=10, verbose_name='Выделение одного типа отчета.'),
        ),
        migrations.AlterField(
            model_name='customizabledirection',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Признак направления в кампании'),
        ),
        migrations.AlterModelTable(
            name='customizabledirection',
            table='selection_direction',
        ),
    ]
