# Generated by Django 3.2.3 on 2021-09-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleClients',
        ),
    ]
