# Generated by Django 3.2.3 on 2022-04-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220405_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttypes',
            name='is_not_set_week',
            field=models.BooleanField(default=False, verbose_name='Статистика всё, что не попало в отчеты'),
        ),
    ]
