# Generated by Django 3.2.3 on 2021-09-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_ads', '0002_auto_20210916_1554'),
        ('yandex_direct', '0001_initial'),
        ('dashboard', '0002_delete_googleclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_tracker_type', models.CharField(choices=[('cl', 'CallTouch'), ('def', '-----')], default='def', max_length=10)),
                ('call_tracker_object_id', models.PositiveIntegerField()),
                ('crm_type', models.CharField(choices=[('amo', 'AmoCrm'), ('exc', 'Excel'), ('def', '-----')], default='def', max_length=10)),
                ('crm_object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('call_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_tracker_content_type', to='contenttypes.contenttype')),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_content_type', to='contenttypes.contenttype')),
                ('google_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.clients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yandex_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.clients')),
            ],
            options={
                'db_table': 'agency_clients',
            },
        ),
    ]
