# Generated by Django 3.2.3 on 2021-09-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('google_ads', '0002_auto_20210916_1554'),
        ('yandex_direct', '0001_initial'),
        ('dashboard', '0003_agencyclients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclients',
            name='call_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_tracker_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='call_tracker_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='call_tracker_type',
            field=models.CharField(choices=[('cl', 'CallTouch'), ('def', '-----')], default='def', max_length=10, verbose_name='Тип коллтрекера'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='crm_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='crm_type',
            field=models.CharField(blank=True, choices=[('amo', 'AmoCrm'), ('exc', 'Excel'), ('def', '-----')], default='def', max_length=10, null=True, verbose_name='Тип crm системы'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='google_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_ads.clients', verbose_name='Логин клиента в google ads'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название клиента'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='yandex_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.clients', verbose_name='Логин клиента в yandex direct'),
        ),
    ]
