# Generated by Django 3.2.3 on 2021-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210917_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclients',
            name='call_tracker_type',
            field=models.CharField(choices=[('cl', 'CallTouch')], max_length=10, verbose_name='Тип коллтрекера'),
        ),
        migrations.AlterField(
            model_name='agencyclients',
            name='crm_type',
            field=models.CharField(blank=True, choices=[('amo', 'AmoCrm'), ('exc', 'Excel')], max_length=10, null=True, verbose_name='Тип crm системы'),
        ),
    ]
