# Generated by Django 3.2.3 on 2021-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211014_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclients',
            name='call_tracker_type',
            field=models.CharField(choices=[('cl', 'CallTouch'), ('co_m', 'Comagic')], max_length=10, verbose_name='Тип коллтрекера'),
        ),
    ]
