# Generated by Django 3.2.3 on 2021-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211117_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclients',
            name='call_tracker_type',
            field=models.CharField(blank=True, choices=[('cl', 'CallTouch'), ('co_m', 'Comagic')], max_length=10, null=True, verbose_name='Тип коллтрекера'),
        ),
    ]
