# Generated by Django 3.2.3 on 2021-12-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_agencyclients_call_tracker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('tag', models.CharField(max_length=256, verbose_name='Tag проекта в utm метке')),
                ('agency_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients')),
            ],
            options={
                'db_table': 'client_projects',
                'ordering': ['name'],
            },
        ),
    ]
