# Generated by Django 3.2.3 on 2021-12-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_clientprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_common', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('is_channel', models.BooleanField(default=False, verbose_name='Статистика по каналам')),
                ('is_campaign', models.BooleanField(default=False, verbose_name='Статистика по кампаниям')),
                ('is_direction', models.BooleanField(default=False, verbose_name='Статистика по направлениям')),
                ('is_comagic_other', models.BooleanField(default=False, verbose_name='Статистика Comagic other')),
                ('is_period', models.BooleanField(default=False, verbose_name='Статистика по периодам')),
                ('is_project_channel', models.BooleanField(default=False, verbose_name='Статистика по каналам проекта')),
                ('is_project_by_day', models.BooleanField(default=False, verbose_name='Статистика по дням проекта')),
                ('agency_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients')),
            ],
            options={
                'db_table': 'report_types',
            },
        ),
    ]
