# Generated by Django 3.2.3 on 2021-12-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_reporttypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyclients',
            name='call_tracker',
        ),
        migrations.RemoveField(
            model_name='agencyclients',
            name='call_tracker_object_id',
        ),
        migrations.RemoveField(
            model_name='agencyclients',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='agencyclients',
            name='crm_object_id',
        ),
    ]
