# Generated by Django 3.2.3 on 2022-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211230_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttypes',
            name='is_brand_nvm',
            field=models.BooleanField(default=False, verbose_name='Статистика за месяц для NVM'),
        ),
        migrations.AddField(
            model_name='reporttypes',
            name='is_month_nvm',
            field=models.BooleanField(default=False, verbose_name='Статистика по месяцам для NVM'),
        ),
        migrations.AddField(
            model_name='reporttypes',
            name='is_week_nvm',
            field=models.BooleanField(default=False, verbose_name='Статистика по неделям для NVM'),
        ),
    ]
