# Generated by Django 3.2.3 on 2022-01-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220121_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=256, verbose_name='Название кампании, по которому выделится направление')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование таблицы')),
                ('agency_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients')),
            ],
            options={
                'db_table': 'customizable_direction',
            },
        ),
    ]
