# Generated by Django 3.2.3 on 2022-01-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0003_alter_metrics_spent'),
        ('dashboard', '0012_auto_20220121_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclients',
            name='vk_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vk.clients', verbose_name='Логин клиента в vk ads'),
        ),
    ]
