# Generated by Django 3.2.3 on 2022-01-30 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0004_auto_20220130_2046'),
        ('dashboard', '0013_agencyclients_vk_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclients',
            name='vk_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vk.clients', verbose_name='Логин клиента в vk ads'),
        ),
    ]
