# Generated by Django 3.2.3 on 2022-01-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_customizabledirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizabledirection',
            name='direction',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название кампании, по которому выделится направление'),
        ),
    ]
