# Generated by Django 3.2.3 on 2022-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_customizabledirection_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizabledirection',
            name='direction',
            field=models.CharField(default='', max_length=256, verbose_name='Название кампании, по которому выделится направление'),
        ),
    ]
