# Generated by Django 3.2.3 on 2022-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_customizabledirection_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizabledirection',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='customizabledirection',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Общее'),
        ),
        migrations.AlterField(
            model_name='customizabledirection',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Название кампании, по которому выделится направление'),
        ),
    ]
