# Generated by Django 3.2.3 on 2022-02-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_target', '0005_metrics_agency'),
        ('dashboard', '0018_agencyclients_my_target_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclients',
            name='my_target_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_target.clients', verbose_name='Логин клиента в my-target'),
        ),
    ]
