# Generated by Django 3.2.3 on 2022-02-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_agencyclients_my_target_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttypes',
            name='is_smm_nvm',
            field=models.BooleanField(default=False, verbose_name='Статистика по смм для NVM'),
        ),
        migrations.AddField(
            model_name='reporttypes',
            name='is_target_nvm',
            field=models.BooleanField(default=False, verbose_name='Статистика по таргетированной рекламе для NVM'),
        ),
    ]
