# Generated by Django 3.2.3 on 2022-03-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_agencyclients_vk_client'),
        ('dashboard', '0020_auto_20220221_2158'),
    ]

    operations = [
    ]
