# Generated by Django 3.2.3 on 2022-01-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=256)),
                ('account_id', models.IntegerField(verbose_name='ID рекламного аккаунта VK')),
                ('token_vk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk.tokenvk')),
            ],
            options={
                'db_table': 'vk_ads_accounts',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'vk_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=models.Model, to='vk.campaign')),
            ],
            options={
                'db_table': 'vk_metrics',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='ID клиента VK')),
                ('name', models.CharField(max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk.adsaccounts')),
            ],
            options={
                'db_table': 'vk_clients',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk.clients'),
        ),
    ]
