# Generated by Django 3.2.3 on 2022-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0002_auto_20220130_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='spent',
            field=models.FloatField(),
        ),
    ]
