# Generated by Django 3.2.3 on 2022-01-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0003_alter_metrics_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='impressions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='spent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
