# Generated by Django 3.2.3 on 2022-02-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('client_secret', models.TextField()),
                ('client_id', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_target_agency_token',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('campaign_id', models.TextField()),
            ],
            options={
                'db_table': 'my_target_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=256)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_target.agencytoken')),
            ],
            options={
                'db_table': 'my_target_clients',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spent', models.FloatField()),
                ('date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_target.campaigns')),
            ],
            options={
                'db_table': 'my_target_metrics',
            },
        ),
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_target.agencytoken')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_target.clients')),
            ],
            options={
                'db_table': 'my_target_client_token',
            },
        ),
        migrations.AddField(
            model_name='campaigns',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_target.clients'),
        ),
    ]
