# Generated by Django 3.2.3 on 2022-02-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_target', '0002_clients_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttoken',
            name='agency',
        ),
    ]
