# Generated by Django 3.2.3 on 2022-02-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_target', '0004_auto_20220214_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_target.agencytoken'),
            preserve_default=False,
        ),
    ]
