# Generated by Django 3.2.3 on 2021-12-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0002_auto_20211228_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelines',
            name='amo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amocrm.amocrm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinestatuses',
            name='amo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amocrm.amocrm'),
            preserve_default=False,
        ),
    ]
