# Generated by Django 3.2.3 on 2021-12-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0004_metrics_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestatuses',
            name='pipeline',
        ),
    ]
