# Generated by Django 3.2.3 on 2022-01-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0005_remove_pipelinestatuses_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestatuses',
            name='pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amocrm.pipelines'),
            preserve_default=False,
        ),
    ]
