# Generated by Django 3.2.3 on 2022-02-01 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20220201_1605'),
        ('amocrm', '0007_auto_20220112_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amocrm',
            name='agency_client',
        ),
        migrations.AddField(
            model_name='amocrm',
            name='agency_client',
            field=models.ManyToManyField(db_table='amo_crm_and_agency_client', to='dashboard.AgencyClients'),
        ),
    ]
