# Generated by Django 3.2.3 on 2022-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0008_auto_20220201_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrm',
            name='name',
            field=models.CharField(default='NVM', max_length=256, verbose_name='Наименование клиента'),
            preserve_default=False,
        ),
    ]
