# Generated by Django 3.2.3 on 2021-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('hostname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comagic_api_token',
            },
        ),
        migrations.CreateModel(
            name='ComagicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone_number', models.CharField(max_length=50, verbose_name='Контактный номер')),
                ('gclid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Click Identifier')),
                ('yclid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yandex Click Identifier')),
                ('ymclid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yandex Market Click Identifier')),
                ('campaign_name', models.TextField(blank=True, null=True, verbose_name='Название рекламной кампании')),
                ('campaign_id', models.IntegerField(verbose_name='ID рекламной кампании')),
                ('utm_source', models.TextField(blank=True, null=True, verbose_name='Источник кампании')),
                ('utm_medium', models.TextField(blank=True, null=True, verbose_name='Канал кампании')),
                ('utm_term', models.TextField(blank=True, null=True, verbose_name='Ключевое слово кампании')),
                ('utm_campaign', models.TextField(blank=True, null=True, verbose_name='Название кампании')),
            ],
            options={
                'db_table': 'comagic_report',
            },
        ),
    ]
