# Generated by Django 3.2.3 on 2021-10-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comagicreport',
            name='api_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comagic.apitoken'),
            preserve_default=False,
        ),
    ]
