# Generated by Django 3.2.3 on 2021-10-15 10:40

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0002_comagicreport_api_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='comagicreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
