# Generated by Django 3.2.3 on 2021-10-15 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0004_remove_comagicreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comagicreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
