# Generated by Django 3.2.3 on 2021-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0007_alter_comagicreport_contact_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comagicreport',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_operation',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
