# Generated by Django 3.2.3 on 2021-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0008_auto_20211020_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='comagicreport',
            name='is_lost',
            field=models.BooleanField(default=True),
        ),
    ]
