# Generated by Django 3.2.3 on 2021-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0009_comagicreport_is_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comagic_attributes_report',
            },
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='is_lost',
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_chat',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор чата'),
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_site',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор сайта'),
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='source_type',
            field=models.CharField(choices=[('call', 'Звонок'), ('chat', 'Чат'), ('site', 'Сайт')], default='call', max_length=10, verbose_name='Источник заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comagicreport',
            name='id_operation',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор звонка'),
        ),
        migrations.AlterModelTable(
            name='comagicreport',
            table='comagic_call_report',
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='attributes',
            field=models.ManyToManyField(to='comagic.AttributesReport', verbose_name='Атрибуты обращения'),
        ),
    ]
