# Generated by Django 3.2.3 on 2021-10-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0010_auto_20211021_1940'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comagicreport',
            table='comagic_report',
        ),
    ]
