# Generated by Django 3.2.3 on 2021-10-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0012_comagicreport_start_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comagicreport',
            name='start_date_time',
        ),
    ]
