# Generated by Django 3.2.3 on 2021-10-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0013_remove_comagicreport_start_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comagicreport',
            name='start_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
