# Generated by Django 3.2.3 on 2021-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0015_alter_comagicreport_start_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comagicreport',
            name='contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='id_chat',
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='id_operation',
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='id_site',
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_handling',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор обращения'),
        ),
        migrations.AlterField(
            model_name='comagicreport',
            name='source_type',
            field=models.CharField(choices=[('call', 'Звонок'), ('chat', 'Чат'), ('offline_message', 'Сайт'), ('goal', 'Цель')], max_length=20, verbose_name='Источник заявки'),
        ),
    ]
