# Generated by Django 3.2.3 on 2021-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0017_comagicreport_visitor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comagicreport',
            name='id_handling',
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_chat',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор чата'),
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_operation',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор звонка'),
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_site',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор сайта'),
        ),
        migrations.AlterField(
            model_name='comagicreport',
            name='source_type',
            field=models.CharField(choices=[('call', 'Звонок'), ('chat', 'Чат'), ('site', 'Сайт')], max_length=10, verbose_name='Источник заявки'),
        ),
    ]
