# Generated by Django 3.2.3 on 2021-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0018_auto_20211022_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='comagicreport',
            name='messages_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во сообщений в чате'),
        ),
    ]
