# Generated by Django 3.2.3 on 2021-10-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0019_comagicreport_messages_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('site_domain_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comagic_domain_report',
            },
        ),
        migrations.RemoveField(
            model_name='comagicreport',
            name='id_site',
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='id_offline_application',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Уникальный идентификатор оффлайн заявки'),
        ),
        migrations.AddField(
            model_name='comagicreport',
            name='site_domain_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comagic.domainreport'),
            preserve_default=False,
        ),
    ]
