# Generated by Django 3.2.3 on 2021-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comagic', '0020_auto_20211025_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comagicreport',
            name='source_type',
            field=models.CharField(choices=[('call', 'Звонок'), ('chat', 'Чат'), ('site', 'Сайт'), ('cutaways', 'Визитки'), ('other', 'Другие лиды')], max_length=10, verbose_name='Источник заявки'),
        ),
    ]
