# Generated by Django 3.2.3 on 2021-11-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211117_1301'),
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionemail',
            name='agency_client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributionemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почтовый ящик'),
        ),
    ]
