# Generated by Django 3.2.3 on 2021-12-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0002_auto_20211126_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='periodic_task',
        ),
    ]
