# Generated by Django 3.2.3 on 2021-09-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('site_id', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calltouch_api_token',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=20)),
                ('call_id', models.TextField()),
                ('source', models.CharField(max_length=250)),
                ('utm_source', models.CharField(max_length=250)),
                ('utm_campaign', models.TextField()),
                ('google_client_id', models.TextField()),
                ('yandex_client_id', models.TextField()),
                ('user_agent', models.TextField()),
                ('date', models.DateField()),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calltouch.apitoken')),
            ],
            options={
                'db_table': 'calltouch_reports',
            },
        ),
    ]
