# Generated by Django 3.2.3 on 2021-06-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calltouch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='site_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
