# Generated by Django 3.2.3 on 2021-12-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211230_1038'),
        ('calltouch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='agency_client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclients'),
            preserve_default=False,
        ),
    ]
