# Generated by Django 3.2.3 on 2021-06-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calltouch', '0002_apitoken_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.DateField(default='2020-06-22'),
            preserve_default=False,
        ),
    ]
