# Generated by Django 3.2.3 on 2021-06-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calltouch', '0003_reports_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='user',
        ),
        migrations.AddField(
            model_name='reports',
            name='api_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calltouch.apitoken'),
            preserve_default=False,
        ),
    ]
