# Generated by Django 3.2.3 on 2021-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calltouch', '0004_auto_20210622_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='call_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='google_client_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='user_agent',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='yandex_client_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
