# Generated by Django 3.2.3 on 2021-09-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ad_group_id', models.TextField()),
            ],
            options={
                'db_table': 'yandex_ad_groups',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key_word_id', models.TextField()),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.adgroups')),
            ],
            options={
                'db_table': 'yandex_key_words',
            },
        ),
        migrations.CreateModel(
            name='YandexDirectToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yandex_direct_token',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField()),
                ('cost', models.FloatField()),
                ('ctr', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('date', models.DateField()),
                ('key_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.keywords')),
            ],
            options={
                'db_table': 'yandex_metrics',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('client_id', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yandex_clients',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('campaign_id', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.clients')),
            ],
            options={
                'db_table': 'yandex_campaigns',
            },
        ),
        migrations.AddField(
            model_name='adgroups',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_direct.campaigns'),
        ),
    ]
