# Generated by Django 3.2.3 on 2021-10-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['name']},
        ),
    ]
