# Generated by Django 3.2.3 on 2021-06-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_direct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user',
        ),
        migrations.RemoveField(
            model_name='googleadstoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Campaigns',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='GoogleAdsToken',
        ),
    ]
