# Generated by Django 3.2.3 on 2021-11-17 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yandex_direct', '0002_alter_clients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexdirecttoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_token_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
