# Generated by Django 3.2.3 on 2021-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_direct', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yandexdirecttoken',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='yandexdirecttoken',
            name='refresh_token',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
