# Generated by Django 3.2.3 on 2022-03-22 06:21

from django.db import migrations, models
import django.db.models.deletion
from ..models import Campaigns


class Migration(migrations.Migration):
    dependencies = [
        ('yandex_direct', '0003_alter_yandexdirecttoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='ad_group',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='ctr',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='key_word',
        ),
        migrations.AddField(
            model_name='metrics',
            name='campaign',
            field=models.ForeignKey(default=Campaigns.objects.first().pk, on_delete=django.db.models.deletion.CASCADE,
                                    to='yandex_direct.campaigns'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdGroups',
        ),
        migrations.DeleteModel(
            name='KeyWords',
        ),
    ]
