# Generated by Django 3.2.3 on 2021-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_customer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
